### ISSUE TITLE
How to diagnose connection problems?

### ISSUE THREAD

**Issue by ferulisses** [nakagami/pyfirebirdsql#102]
Hi,

I'm trying to connect to a remote Firebird Server, version 3.0.10, I passed all parameters, but I'm getting the Unauthorized message, even knowing that all info are correct.

I can connect to this server using the firebird-driver and command line utility using the same credentials, but not using firebirdsql:

import firebirdsql
con1 = firebirdsql.connect(host="x.x.x.x", port=xyz, database="ALIAS", user="USER", password="PASS", charset="UTF-8")
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "APP_PATH/api/venv/lib64/python3.9/site-packages/firebirdsql/__init__.py", line 95, in connect
    conn = Connection(**kwargs)
  File "APP_PATH/api/venv/lib64/python3.9/site-packages/firebirdsql/fbcore.py", line 649, in __init__
    raise e
  File "APP_PATH/api/venv/lib64/python3.9/site-packages/firebirdsql/fbcore.py", line 645, in __init__
    self._parse_connect_response()
  File "APP_PATH/api/venv/lib64/python3.9/site-packages/firebirdsql/wireprotocol.py", line 670, in _parse_connect_response
    (h, oid, buf) = self._op_response()
  File "APP_PATH/api/venv/lib64/python3.9/site-packages/firebirdsql/wireprotocol.py", line 1143, in _op_response
    raise OperationalError('Unauthorized')
firebirdsql.OperationalError: Unauthorized
```

- Firebird Server version 3.0.10 on Windows
- pyfirebirdsql version 1.2.2
- Python 3.9

There is any parameter to better diagnose this problem?

**Comment by 66zai** [comment]
This is an automatic reply, confirming that your e-mail was received.Thank you----------------------------------------------------------您的E-mail我已经收到，如果看到定会很快给您答复。

**Comment by nakagami** [comment]
What is the value of AuthServer in firebird.conf?
It should contain one of Srp256, Srp, or Legacy_Auth

for example
```
AuthServer = Srp256,Srp,Legacy_Auth
```

**Comment by ferulisses** [comment]
I don't know, I don't have access to the server files. There is any param that I can use to try alternate auth methods?

**Comment by nakagami** [comment]
Since the driver is authenticating with a method that has been negotiated and agreed upon by server and clinent both, there does not seem to be a better parameter specification.

**Comment by nakagami** [comment]
I don't have windows to test it on, so I'm hoping someone who uses it on windows can give me some advice...

I don't think it will work at all on windows.

**Comment by 879372** [comment]
No meu tem esses parametros no arquivo  .conf mesmo assim aparece Unauthorized

**Comment by ferulisses** [comment]
Eu troquei para o driver oficial do Firebird (firebird-driver) e funcionou.

Esse driver aqui tinha uma coisa que eu tinha gostado, que era o fetchonemap() que retorna um dict do registro, enquanto que o fetchone() retorna um tuple, mas depois no driver oficial descobri que tem o método cursor.to_dict() que resolveu.

---
I changed to the official Python firebird-driver and it worked for me, I don't think that is worth the time to debug and fix this issue.
