### ISSUE TITLE
Intermittent `AttributeError` in `get_crypt` function on `windows` in multi-threaded code.

### ISSUE THREAD

**Issue by DeadNews** [nakagami/pyfirebirdsql#104]
## Description

Firstly, thank you for your work on this project.

I've encountered an issue with the `get_crypt` function in `firebirdsql/wireprotocol.py`.

https://github.com/nakagami/pyfirebirdsql/blob/f2274ae7f1f070234136f8f9ad544096728b7b5d/firebirdsql/wireprotocol.py#L68-L78

On `windows`, this function _occasionally_ crashes with an `AttributeError` in multi-threaded code:

```py
...\firebirdsql\wireprotocol.py", line 71, in get_crypt

    return crypt.crypt(plain, '9z')[2:]

           ^^^^^^^^^^^

AttributeError: module 'crypt' has no attribute 'crypt'
```

## Possible Solutions

1. Import the `crypt` function directly to [avoid](https://docs.python.org/3/library/exceptions.html#ImportError) the `AttributeError`:

```py
    try:
        from crypt import crypt
        return crypt(plain, '9z')[2:]
    except ImportError:
        pass
```

2. Add `AttributeError` to the exception handling to catch this error:

```py
    try:
        import crypt
        return crypt.crypt(plain, '9z')[2:]
    except (AttributeError, ImportError):
        pass
```

3. Consider not using the `crypt` module by default, for the reasons described in [deprecation notes](https://peps.python.org/pep-0594/#crypt).

## Environment

- OS: Windows
- Python version: `3.11`
- Firebird server: `2.5.9`
- firebirdsql version: `1.2.3`

## Additional context

ref: https://github.com/nakagami/pyfirebirdsql/issues/99

**Comment by nakagami** [comment]
I appreciate your report.
What version of Firebird are you using?

**Comment by DeadNews** [comment]
@nakagami 
I added this information to the Environment section.

**Comment by nakagami** [comment]
If you modify https://github.com/nakagami/pyfirebirdsql/commit/949d7032721caf96a99214443fb398dd3dcb616c and 
```pip install the passlib```
will it work?

**Comment by DeadNews** [comment]
https://github.com/nakagami/pyfirebirdsql/blob/949d7032721caf96a99214443fb398dd3dcb616c/firebirdsql/wireprotocol.py#L69-L72

It will crash with an `ImportError`.


To prevent it from crashing, you can use approaches from point `1` or `2` in the Possible Solutions section.

https://github.com/nakagami/pyfirebirdsql/blob/949d7032721caf96a99214443fb398dd3dcb616c/firebirdsql/wireprotocol.py#L74-L77

Yes, this works on `windows` with `passlib` installed.

**Comment by nakagami** [comment]
Now 1.2.4 released.
Please install and check it.
