### ISSUE TITLE
Can't use DB events

### ISSUE THREAD

**Issue by VladimirMbf** [nakagami/pyfirebirdsql#108]
Hello @nakagami !

Would you kindly help me please to find the reason for the issue that occurs when I trying to initialize event_conduit (after successfully db connection), 
module event_conduit.py
line 95        self.connection._op_connect_request()
line 96        (_, _, buf) = self.connection._op_response()

at line 96 there is forever response waiting from db after sending package at line 95 (and nothing else is happens)

Also, for some reason, in versions > 1.2.2, the fbcore module requires the "select" module, which is missing as an import 

Update:
One more thing: when I try to run event_conduit from pyfirebirdsql driver, no other drivers like fdb, firebird-driver can handle events either (just hang at event_conduit initialization step), only restarting server side database process resumes working with events (but only for fdb and firebird-driver drivers, pyfirebirdsql dosn't work with db events, would be great to find and fix this issue for pyfirebirdsql please)

**Comment by nakagami** [comment]
Here is the test code, it seems to be working as intended.
https://github.com/nakagami/pyfirebirdsql/blob/master/firebirdsql/tests/test_event.py#L79

Can you cut out and present the code where the infinite loop where the phenomenon is reproduced occurs?

Ideally it would be nice to have it in the test code, but it is not essential.

**Comment by nakagami** [comment]
If you add print() as follows, please also tell us what you see
```
diff --git a/firebirdsql/event_conduit.py b/firebirdsql/event_conduit.py
index cff4d9d..d3a9f5b 100644
--- a/firebirdsql/event_conduit.py
+++ b/firebirdsql/event_conduit.py
@@ -107,6 +107,7 @@ class EventConduit(WireProtocolMixin):
                 [address[i: i+4] for i in range(0, len(address), 4)]
             )

+        print(ip_address, port)
         self.sock = SocketStream(ip_address, port, timeout)
         if event_id:
             self.event_id = event_id
```

**Comment by nakagami** [comment]
Applying this fix seems to work correctly.　https://github.com/nakagami/pyfirebirdsql/commit/5328a10b38d35e044e947eaa27a4029a6634164f

But, I would be happy if you test with recent master branch.

**Comment by VladimirMbf** [comment]
@nakagami thank you, now is ok, but family is different, maybe ipv6 mapping to ipv4 have different family too (I have \x17\x00 in my case)?

**Comment by VladimirMbf** [comment]
One more thing, just for your information, when I'm getting any event first it comes like {"some_event": 1} then second time always {"some_event": 0} - one event fires twice, as I know other drivers always increasing count of one event, but in my case I see only 1 and 0 in event count every time (right now I'm waiting only {"some_event": 1} ignoring 0) to catch event once

**Comment by nakagami** [comment]
\x17\x00 seems to be AF_IRDA and I don't know why this is being received in your environment, but it seems like it should be treated like AF_INET6.
Fixed source code. Is this correct? 

I have never experienced receiving the result 
{"some_event": 0}
But sometimes recieve a few event together, such as {"some_event": 2},
So, it is better to use the number here to determine how many events have occurred, rather than the number of times you have been received.
