### ISSUE TITLE
`ImportError`: cannot import name `aio` from partially initialized module `firebirdsql` (most likely due to a circular import)

### ISSUE THREAD

**Issue by DeadNews** [nakagami/pyfirebirdsql#109]
https://github.com/nakagami/pyfirebirdsql/blob/2a3d86a96b6f14449f246d3948813ba8c362a233/firebirdsql/__init__.py#L40

```console
$ pip install --no-cache-dir "firebirdsql (==1.3.0)"

          from firebirdsql import aio
      ImportError: cannot import name 'aio' from partially initialized module 'firebirdsql' (most likely due to a circular import)
```

[Tests environment](https://github.com/DeadNews/firebirdsql-run/actions/runs/10422204368/job/28866173168?pr=159#step:7:108).

**Comment by nakagami** [comment]
Thank you.
I wasn't aware of that.

Now, v1.3.1 released. please install recent package (1.3.1)

It's a stopgap measure, but should be fine for those who use it.
