### ISSUE TITLE
Documentation incorrect about dialect argument for "connection"

### ISSUE THREAD

**Issue by funkybob** [nakagami/pyfirebirdsql#55]
The documentation claims you can pass dialect=? to control the dialect level of the connection.
https://pyfirebirdsql.readthedocs.org/en/latest/python-db-api-compliance.html?highlight=dialect#firebirdsql.connect

However, if you try to actually do this, the Connection object raises an exception:

    TypeError: __init__() got an unexpected keyword arguments 'dialect'

From a quick grep of the git repo, it appears the dialect is hard-coded to 3

firebirdsql/wireprotocol.py:702:        p.pack_int(3)   # dialect = 3
firebirdsql/wireprotocol.py:770:        p.pack_int(3)   # dialect = 3

**Comment by nakagami** [comment]
Sorry document is incorrect.

Conenction parameter dialect 1 and 2 is too old and deprecated.
So I hope to modify this document, remove 'dialect' parameter.

Are you want and use dialect parameter ?

**Comment by funkybob** [comment]
Fortunately the dialect issue turned out to be a furfy, and it's some other issue raising the error that led me to this.

I do not need the dialect flag.

Thank you.

**Comment by nakagami** [comment]
Thank you.

Remove 'dialect' parameter in the document.
