### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by movermeyer** [nakagami/pyfirebirdsql#60]
Traceback (most recent call last):
      <some lines elided for privacy>
      File "C:\Python27\lib\site-packages\firebirdsql\fbcore.py", line 367, in fetchall
        return [tuple(r) for r in self._fetch_records]
      File "C:\Python27\lib\site-packages\firebirdsql\fbcore.py", line 192, in _fetch_generator
        stmt.handle, stmt.xsqlda)
    ValueError: too many values to unpack
    
This is a result of this line in fbcore.py:

    (rows, more_data) = connection._op_fetch_response(stmt.handle, stmt.xsqlda)
    
Which assumes that there are only 2 values returned. However, _op_fetch_response() can return 3 values since it can return the result of _parse_op_response() (line 780 of wireprotocol.py).

**Comment by nakagami** [comment]
Thanks,  I understand that code has something wrong.

I want test code, Can you show a sample code ?

**Comment by movermeyer** [comment]
I've managed to produce a simple enough test case that demonstrates the issue.

1. Create a new database
2. Run the SQL commands found [here](https://gist.github.com/movermeyer/a41023214ee3ef6ab769).
3. Run the [Python script found here](https://gist.github.com/movermeyer/6a6603f0504f5fa94ae1) against the database.

Note that it fails if you try to select more than 400 BLOBs.

**Comment by nakagami** [comment]
Thank you.
I have released 0.9.9 just now.
Please test with it.

**Comment by movermeyer** [comment]
The [commit you made to fix this](https://github.com/nakagami/pyfirebirdsql/commit/bb619bf4b1831151c35feea3075b93df8a932c41) introduced an infinite loop.

1. Create a new database
2. Run the SQL commands [found here](https://gist.github.com/movermeyer/a41023214ee3ef6ab769).
3. Run the [Python script found here](https://gist.github.com/movermeyer/220f87b34eba730bb67b) against the database.

**Comment by nakagami** [comment]
I am certain of this problem.

**Comment by nakagami** [comment]
Probably fixed at version 0.9.11

**Comment by movermeyer** [comment]
It now seems to work. My program is once again working without issue (for the first time since before 9.2).

:)
