### ISSUE TITLE
Legacy auth: failure

### ISSUE THREAD

**Issue by kai3341** [nakagami/pyfirebirdsql#73]
Hex dump difference: https://box.unet.by/f/15/15157_474.png
Active window authorized successfully: it's python-fdb module
Sorry, i don't know how to fix this. Maybe you can give me initial help and i shall continue

**Comment by nakagami** [comment]
Paste example code and teache me your python environment.

**Comment by kai3341** [comment]
I forked django-fdb:
`	'energy_local': {    # Local backup. Works ok
		'ENGINE' :		'django-firebirdsql',
		'NAME' :		'energy',
		'USER' :		'energy',
		'PASSWORD' :	'*********',
		'HOST' : 		'0.0.0.0',
		'PORT' :		'3050',
		'ASKUE' :		'mikron',    #XXX Non-django field
		'CONN_MAX_AGE':	None,
		'OPTIONS' : {
			'charset' : 'WIN1251',
		},
	},

	'a2000_local': {    # Local backup. Works ok
		'ENGINE' :		'django-firebirdsql',
		'NAME' :		'A2000',
		'USER' :		'A2000',
		'PASSWORD' :	'*********',
		'HOST' : 		'0.0.0.0',
		'PORT' :		'3050',
		'ASKUE' :		'konus',	#XXX non-django field, database backend
		'CONN_MAX_AGE':	None,
		'OPTIONS' : {
			'charset' : 'WIN1251',
		},
	},

	'energy': {    # This database doesn't work.
		'ENGINE' :		'django-firebirdsql',
		'NAME' :		'energy',
		'USER' :		'energy',
		'PASSWORD' :	'*********',
		'HOST' : 		'asu-205-5',
		'PORT' :		'3051',
		'ASKUE' :		'mikron',	#XXX non-django field, database backend
		'CONN_MAX_AGE':	None,
		'OPTIONS' : {
			'charset' : 'WIN1251',
		},
	},

	'a2000': {    # This database works ok
		'ENGINE' :		'django-firebirdsql',
		'NAME' :		'a2000',
		'USER' :		'a2000',
		'PASSWORD' :	'*********',
		'HOST' : 		'asu-205-5',
		'PORT' :		'3052',
		'ASKUE' :		'konus',	#XXX non-django field, database backend
		'CONN_MAX_AGE':	None,
		'OPTIONS' : {
			'charset' : 'WIN1251',
		},
	},`
All this connections works with python-fdb

**Comment by nakagami** [comment]
Umm, sorry I do'nt why about django.

But at least 2 option settings need in firebird.conf

AuthServer = Legacy_Auth
WireCrypt = Disabled

**Comment by kai3341** [comment]
Server side, right?

**Comment by level420** [comment]
@kai3341 did you solve this? I'm running into the same problem: connecting to firebird 2 works, but not to firebird 3. The firebird server has configured legacy auth:
```
ServerMode = SuperClassic
WireCrypt = Disabled
WireCompression = false
AuthServer = Legacy_Auth, Srp, Win_Sspi
AuthClient = Legacy_Auth, Srp, Win_Sspi
UserManager = Legacy_UserManager, Srp
```

**Comment by kai3341** [comment]
@level420 i didn't. I switched database driver back to fdb.

**Comment by nakagami** [comment]
I want information about

- Server OS 
- Client OS

**Comment by nakagami** [comment]
The reason is unknown, but close it.
