### ISSUE TITLE
Add support for case sensitive user names

### ISSUE THREAD

**Issue by mrotteveel** [nakagami/pyfirebirdsql#76]
Firebird 3 introduced case sensitive user names, this is currently not supported by pyfirebirdsql. For case sensitive user names, Firebird applies the same rules as for case sensitive object names: they are quoted in double quotes.

Example

```
create user "CaseSensitive" password 'password' using plugin Srp;
create user caseinsensitive password 'password' using plugin Srp;
```

This creates two user, the case sensitive username `CaseSensitive` and the case insensitive `caseinsensitive` (or more correct: `CASEINSENSITIVE`).

Current attempts to use case sensitive usernames (eg as `user='"CaseSensitive"'` in a `connect`) yield error _"TypeError: a bytes-like object is required, not 'NoneType'"_ (see also #75). This is because pyfirebirdsql upper cases the user names in various places.

Instead, the following rules should be applied:

- `CNCT_login`: pass user name as is (preserve quotes if present)
- `isc_dpb_user_name`: pass user name as is (preserve quotes if present)
- `isc_spb_user_name`: pass user name as is (preserve quotes if present)
- Usage in SRP client proof: unquoted usernames: uppercase, quoted usernames: strip and unescape double quotes and preserve current case (that is `caseinsensitive ` -> `CASEINSENSITIVE`, `"CaseSensitive"` -> `CaseSensitive` and `"Contains""Quote"` -> `Contains"Quote`

**Comment by mrotteveel** [comment]
If I can find the time and energy I'll create a pull request to address this.

**Comment by nakagami** [comment]
Thanks, Mark.
Perhaps I fix it.

**Comment by mrotteveel** [comment]
Thanks! I left a comment on the commit, though that is really an obscure edge case.

**Comment by nakagami** [comment]
Thanks again, Mark
Unquote quoted double quote.
