### ISSUE TITLE
stuck on socket receive when inserting blob data

### ISSUE THREAD

**Issue by frosenek** [nakagami/pyfirebirdsql#77]
I'm currently working on a Firebird 2.5 database with Python 3.6.4 and have trouble inserting image data into a binary blob field.

You should be able to observe the behaviour I'm getting by changing the test_blob() function in test_basic.py from 
` cur.execute("update blob0_test set b = ?", (b'x' * (MAX_CHAR_LENGTH+1), ))`
to
` cur.execute("update blob0_test set b = ?", (b'x' * (MAX_CHAR_LENGTH+2), ))`

**Comment by nakagami** [comment]
Please show me MAX_CHAR_LENGTH.

**Comment by frosenek** [comment]
MAX_CHAR_LENGTH = 32767
BLOB_SEGMENT_SIZE = 32000

No error message. It tries to receive data through SocketStream.recv() without timing out and thereby freezes the application.

in the method _create_blob(self, trans_handle, b) of the class WireProtocol the method self._op_response() gets called which in turn calls self.recv_channel(4). self.recv_channel() never returns in this case because it waits for the socket to receive data without timing out.

**Comment by nakagami** [comment]
Oh, thanks 
They are in consts.py
