### ISSUE TITLE
Custom TPB not supported?

### ISSUE THREAD

**Issue by janvolec** [nakagami/pyfirebirdsql#94]
The [documentation](https://pyfirebirdsql.readthedocs.io/en/latest/beyond-python-db-api.html#explicit-transaction-start) suggests there is a possibility to have customized TPB, however, I guess this is not the case since [REL_0_9_1](https://github.com/nakagami/pyfirebirdsql/releases/tag/REL_0_9_1) ; see [this commit](https://github.com/nakagami/pyfirebirdsql/commit/88bd7b72ae43effd43343c067125e9532195d2f5) . I tried to quickly reverse-engineer the current version (python is not my language #1) and I do not see how to have a custom TPB without some hacking around. Am I missing something? Is there an updated documentation for the library?

**Comment by nakagami** [comment]
Sorry, wrong document.

I'm going to remove the description from the documentation.
Is there a case where you would like to specify tpb?

If there is such a situation, I would consider adding the feature, but since it has never been pointed out to me, I think this feature is not needed.

**Comment by pcisar** [comment]
The ability to define custom TPB is certainly very important, especially if you don't provide any other method to specify VERY important transaction options like TIMEOUT (all transactions you support are WAIT), R/W vs. R/O. 

I also don't understand why isolation level is defined on Connection, so all transactions related to single connection have the the same isolation. It's quite normal  (and key point to use multiple transactions) that transactions have different characteristics, incl. isolation level.

**Comment by nakagami** [comment]
Okay, I understand.

Currently, the TPB value is determined by the isolation_level parameter of the connection, but this is not flexible enough.
Also, you want to be able to specify more granularly on a per-transaction basis.

I would consider allowing TPBs to be specified, as described in the documentation.

**Comment by janvolec** [comment]
Yes, as Pavel have pointed out both the facts I need to hack around to have
different TPBs for different transactions and/or using a 'tpb_nowait' seems
rather unfortunate to me (right now, I was just porting some very old code
designed a long time ago and trying to minimize design changes)

OT: Hi Pavel, very good to see you are still being around (we have met in
Prague good >15 years ago)

**Comment by nakagami** [comment]
@janvolec
Created a pull request to be able to pass TPB.
https://github.com/nakagami/pyfirebirdsql/pull/95

Does this modification achieve what you want to do?

**Comment by janvolec** [comment]
It seems to me one still cannot have one connection with two transactions each using different TPBs,
am I overlooking something?

Jan

**Comment by nakagami** [comment]
Here we are starting a readonly transaction
https://github.com/nakagami/pyfirebirdsql/pull/95/files#diff-a6bddd891ddb6496b0498a0828c7ccf1d9f1e29c8529cff57d418631c8f45fc8R168

...but it doesn't return to the initial (read & write) transaction.

If I do connection.commit() or connection.rollback()
Do you think it would be better to go back to the original state?

I'd be glad to have sample code, as I still don't have the right answer as to how it should be done.

**Comment by nakagami** [comment]
Are the following behaviors expected?
```
connection.begin([...])     <--- custom tpb 1
cur1 = connection.sursor()
cur2.execute("...")          <-- execute with custom tpb 1

connection.begin([...])     <--- custom tpb 2
cur2 = connection.sursor()
cur2.execute("...")         <-- execute with custom tpb 2


connection.begin()          <--- default tpb defined connection.isolation_level
cur = connection.sursor()
cur.execute("...")          <-- execute with default tpb
```

**Comment by nakagami** [comment]
Sorry.
I removed the description of the document.
