### ISSUE TITLE
des encription with passlib

### ISSUE THREAD

**Issue by nakagami** [nakagami/pyfirebirdsql#99]
crypt module will be removed.
https://peps.python.org/pep-0594/

crypt module is used for Legacy_Auth (for Firebird 3 and 4), so use passlib to fallback.

passlib
https://pypi.org/project/passlib/

```
>>> import crypt
>>> crypt.crypt("secret", '9z')
'9zMktUfATCrdY'
```

```
>>> import passlib.hash
>>> passlib.hash.des_crypt.hash("secret", salt='9z')
'9zMktUfATCrdY'
```

**Comment by 66zai** [comment]
This is an automatic reply, confirming that your e-mail was received.Thank you----------------------------------------------------------您的E-mail我已经收到，如果看到定会很快给您答复。
